### ISSUE TITLE
About LMSE attack and

### ISSUE THREAD

**Issue by raindrop313** [yuyi-sd/Robust_Rain_Removal#4]
Hi, thanks for your work, and I have a problem with the  LMSE attack and the LPIPS attack proposed in your paper. Why does LPIPS attack targets machine vision, and LMSE attack targets human vision？

**Comment by yuyi-sd** [comment]
Hi,raindrop. That's correct. LMSE attack aims to perturb the detaining results in terms of MSE loss, which is more on the pixel-wise perturbations. And LPIPS attack aims to perturb the results in the image feature embedding space, and we use the perceptual loss here to evaluate.

**Comment by yuyi-sd** [comment]
> Hi, thanks for your work, and I have a problem with the  LMSE attack and the LPIPS attack proposed in your paper. Why does LPIPS attack targets machine vision, and LMSE attack targets human vision？
